// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhRsJN2FL2dyzq20Brjv_fsY2Xo153AgA',
    appId: '1:697222347127:android:45c190b3dbcbbbe5878972',
    messagingSenderId: '697222347127',
    projectId: 'waterlog-f7fc7',
    storageBucket: 'waterlog-f7fc7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpcMMh3oW2bzKdGUy61DA95Xy_xwcF-Xk',
    appId: '1:697222347127:ios:39bd485c90b4d98d878972',
    messagingSenderId: '697222347127',
    projectId: 'waterlog-f7fc7',
    storageBucket: 'waterlog-f7fc7.firebasestorage.app',
    androidClientId: '697222347127-52bt7rt018b1flnb2cef95ld0jum10tp.apps.googleusercontent.com',
    iosClientId: '697222347127-fpoehvt33cior0koj11li82420c6vo94.apps.googleusercontent.com',
    iosBundleId: 'com.juwon.waterlog',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHFSmWW78Tw1qgmMnAczOoYw2yvDEEh_s',
    appId: '1:697222347127:web:058110a781d1b7ce878972',
    messagingSenderId: '697222347127',
    projectId: 'waterlog-f7fc7',
    authDomain: 'waterlog-f7fc7.firebaseapp.com',
    storageBucket: 'waterlog-f7fc7.firebasestorage.app',
    measurementId: 'G-M5H5MPV07E',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpcMMh3oW2bzKdGUy61DA95Xy_xwcF-Xk',
    appId: '1:697222347127:ios:0ddc1fabee4c8b71878972',
    messagingSenderId: '697222347127',
    projectId: 'waterlog-f7fc7',
    storageBucket: 'waterlog-f7fc7.firebasestorage.app',
    androidClientId: '697222347127-52bt7rt018b1flnb2cef95ld0jum10tp.apps.googleusercontent.com',
    iosClientId: '697222347127-rnaesrn8e0f63asicl0nsj9ln4mmbo3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterlogs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHFSmWW78Tw1qgmMnAczOoYw2yvDEEh_s',
    appId: '1:697222347127:web:f4be238001451c66878972',
    messagingSenderId: '697222347127',
    projectId: 'waterlog-f7fc7',
    authDomain: 'waterlog-f7fc7.firebaseapp.com',
    storageBucket: 'waterlog-f7fc7.firebasestorage.app',
    measurementId: 'G-SHZ3F1V5HC',
  );
}
