// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhRsJN2FL2dyzq20Brjv_fsY2Xo153AgA',
    appId: '1:697222347127:android:6a108be1ba807d67878972',
    messagingSenderId: '697222347127',
    projectId: 'waterlog-f7fc7',
    storageBucket: 'waterlog-f7fc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpcMMh3oW2bzKdGUy61DA95Xy_xwcF-Xk',
    appId: '1:697222347127:ios:0ddc1fabee4c8b71878972',
    messagingSenderId: '697222347127',
    projectId: 'waterlog-f7fc7',
    storageBucket: 'waterlog-f7fc7.firebasestorage.app',
    androidClientId: '697222347127-52bt7rt018b1flnb2cef95ld0jum10tp.apps.googleusercontent.com',
    iosClientId: '697222347127-rnaesrn8e0f63asicl0nsj9ln4mmbo3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterlogs',
  );

}